# Generated by Django 5.0.7 on 2024-07-10 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="hierarchy_level",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                choices=[
                    ("position_1", "Position 1"),
                    ("position_2", "Position 2"),
                    ("position_3", "Position 3"),
                    ("position_4", "Position 4"),
                    ("manager", "Manager"),
                    ("department_head", "Department Head"),
                    ("coo", "Chief Operating Officer (COO)"),
                    ("cfo", "Chief Financial Officer (CFO)"),
                    ("ceo", "Chief Executive Officer (CEO)"),
                    ("chairman", "Chairman"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("name", "hierarchy_level")},
        ),
    ]
