# Generated by Django 5.0.7 on 2024-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "staff_management",
            "0002_position_hierarchy_level_alter_position_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={},
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
