# Generated by Django 5.0.7 on 2024-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0003_alter_employee_options_alter_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
