# Generated by Django 5.0.7 on 2024-07-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0005_alter_employee_email_alter_employee_hired_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                choices=[
                    ("position_1", "Position 1"),
                    ("position_2", "Position 2"),
                    ("position_3", "Position 3"),
                    ("position_4", "Position 4"),
                    ("manager", "Manager"),
                    ("department_head", "Department Head"),
                    ("coo", "Chief Operating Officer (COO)"),
                    ("cfo", "Chief Financial Officer (CFO)"),
                    ("ceo", "Chief Executive Officer (CEO)"),
                    ("chairman", "Chairman"),
                ],
                max_length=128,
                unique=True,
            ),
        ),
    ]
