# Generated by Django 5.0.7 on 2024-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0006_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
