# Generated by Django 5.0.7 on 2024-07-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "staff_management",
            "0007_alter_employee_is_staff_alter_employee_is_superuser",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                choices=[
                    ("Start position", "Start position"),
                    ("manager", "Manager"),
                    ("department_head", "Department Head"),
                    ("coo", "Chief Operating Officer (COO)"),
                    ("cfo", "Chief Financial Officer (CFO)"),
                    ("ceo", "Chief Executive Officer (CEO)"),
                    ("chairman", "Chairman"),
                ],
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("full_name", "email")},
        ),
    ]
