# Generated by Django 5.0.7 on 2024-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0008_alter_position_name_alter_employee_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                choices=[
                    ("position_1", "Start position"),
                    ("manager", "Manager"),
                    ("department_head", "Department Head"),
                    ("coo", "Chief Operating Officer (COO)"),
                    ("cfo", "Chief Financial Officer (CFO)"),
                    ("ceo", "Chief Executive Officer (CEO)"),
                    ("chairman", "Chairman"),
                ],
                max_length=128,
                unique=True,
            ),
        ),
    ]
