# Generated by Django 5.0.7 on 2024-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0009_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
