# Generated by Django 5.0.7 on 2024-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0011_alter_employee_supervisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
