# Generated by Django 5.0.7 on 2024-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0012_alter_employee_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
