# Generated by Django 5.0.7 on 2024-07-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_management", "0013_alter_employee_first_name_alter_employee_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
